12.0 spp customer wallet
coopiteasy/cie-custom pull request #101
Opened 2023-03-16 10:29 UTC by carmenbianca

## Description

## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=10213&action=479&model=project.task&view_type=form&menu_id=536

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

2023-03-24 14:52 UTC, victor-champonnois requested changes
Very complex so I was lost on the logic. I will trust the functionnal tests on that. However I think the code should be made easier to read by commenting or encapsulating in smaller methods.

2023-03-24 14:52 UTC, victor-champonnois commented on spp_portal_customer_wallet/controllers/main.py
> +    return dict(result)
Sorry I don't understand what this function does. Is there a way to make it more explicit ? (a comment or clearer names ?)

2023-03-24 14:52 UTC, victor-champonnois commented on spp_portal_customer_wallet/controllers/main.py
> +        values = super(PortalPosOrderAmount, self)._prepare_portal_layout_values()
Some say it's best to just use `super()` in that case (without parameter). It would be maybe more consistent with our codebase. I don't really care though :)

2023-03-24 14:52 UTC, victor-champonnois commented on spp_portal_customer_wallet/controllers/main.py
> +
It's very hard to understand this code (at least for me). I think it should be encapsulated in a method (or methods) which has a name describing what it does, otherwise it's just too much for my brain :/

2023-03-24 14:52 UTC, victor-champonnois commented on spp_portal_customer_wallet/controllers/main.py
> +
Or you can comments if it's too much refactoring, I just need to be explained in plain english what this does. I think the "per_month" name is very obscure, maybe that is the culprit.

2023-03-24 14:52 UTC, victor-champonnois commented on spp_portal_customer_wallet/models/res_partner.py
> +        """
OK that makes it a bit clearer :)

2023-03-24 14:54 UTC, victor-champonnois commented
@carmenbianca I also think that this module could have a more generic name no ? It's really a new functionality that could be reused.

2023-03-24 15:55 UTC, huguesdk commented
@victor-champonnois thanks for the review. i’m afraid we’re too close to the release for changes. i skimmed through the code and didn’t spot anything dangerous or weird. since it’s a new module and it’s custom (so will be used by only one client), i think it’s ok to release it as is, and your asked changes should be done later in another branch.

2023-03-24 15:59 UTC, victor-champonnois commented
@huguesdk You are right as always hugues :) I approve the PR and get out of the way ;)

2023-03-24 16:00 UTC, victor-champonnois approved these changes

2023-03-24 16:02 UTC, huguesdk commented
sorry if i wasn’t clear. i didn’t mean to approve it, as i agree with your remarks. i just don’t think they should block the release, only that they should be handled later.

2023-03-24 16:04 UTC, victor-champonnois commented
Ah ok I didn't think of this option. Let's do it like that then :)

2023-03-25 21:18 UTC, huguesdk commented
/ocabot merge nobump

2023-03-25 21:36 UTC, huguesdk commented
/ocabot merge nobump

2023-03-25 21:55 UTC, merged