[16.0][MIG] rotordc_autofill_product_variant: migration to 16.0
coopiteasy/cie-custom pull request #117
Opened 2024-11-01 15:35 UTC by huguesdk

## odoo task

[t12917](https://gestion.coopiteasy.be/web#id=12908&model=project.task)

2024-12-06 10:18 UTC, polchampion requested changes
functionaly tested on rotor-v16-test, partial success:
- [x] weight
- [x] volume and dimensions
- [ ] **internal reference**

test report: the internal reference is only copied for the firest variant created. In v16, there is a non-blocking warning when adding an internal reference that is already used. Maybe that's the reason why the internal reference doesn't get copied to variants beyond the first one.

2024-12-06 10:29 UTC, polchampion commented
> functionaly tested on rotor-v16-test, partial success:
> 
>     * [x]  weight
> 
>     * [x]  volume and dimensions
> 
>     * [ ]  **internal reference** [EDIT : it works]
> 
> 
> ~test report: the internal reference is only copied for the firest variant created. In v16, there is a non-blocking warning when adding an internal reference that is already used. Maybe that's the reason why the internal reference doesn't get copied to variants beyond the first one.~

@huguesdk I actually had tested without installing the module. Weight and dimensions are copied anyway, so idk if this part of the code is relevant. Internal reference is copied correctly.

2024-12-06 10:30 UTC, polchampion approved these changes
successful functional test

2024-12-10 10:50 UTC, huguesdk commented
@polchampion thanks to you i discovered a bug in `product_dimension` (OCA/product-attribute#1811) and simplified the code of this module.

2025-10-01 14:24 UTC, remytms approved these changes
LGTM. Cosmetic comment.

2025-10-01 14:24 UTC, remytms commented on rotordc_autofill_product_variant/__manifest__.py
> +    "qweb": [],
These empty keys can be removed.

2025-10-01 14:24 UTC, remytms commented
/ocabot merge nobump

2025-10-01 14:32 UTC, merged