[12.0][ADD] spp_custom: track visibility
coopiteasy/cie-custom pull request #4
Opened 2020-09-11 17:29 UTC by mclaeysb

Track visibility for a bunch of fields, including custom track visibility for M2M and O2M fields.

Not the most beautiful code I've written, but I don't know how to make it cleaner. Tips welcome.

FYI: I'm using `rec.taxes_id` before and after the write, instead of `vals[taxes_id]`, because the latter has complicated `[(6, _, [ids])]` values etc.

2020-09-18 14:08 UTC, robinkeunen requested changes
I think this is the better way to do it :-)

Only problem I see is that you return res from inside the loop although write can only be used on a single record (90% sure on this, not 100%).

```python
@api.multi
def write(self, vals):
    # Custom track visibility for
    # taxes_id (M2M), seller_ids (M2M, supplier_taxes_id (O2M)
    for rec in self:
        ...
        res = super(ProductTemplate, self).write(vals).   # called on self not rec !
        ...
    return res
```

could be


```python

@api.multi
def write(self, vals):
    # Custom track visibility for
    # taxes_id (M2M), seller_ids (M2M, supplier_taxes_id (O2M)
    ...
    res = super(ProductTemplate, product).write(vals)
    ...
    return res
```

2020-09-18 14:08 UTC, robinkeunen commented on spp_custom/models/product.py
> +        for rec in self:
maybe use `for template in self`?

2020-09-23 16:41 UTC, mclaeysb commented
> I think this is the better way to do it :-)
> 
> Only problem I see is that you return res from inside the loop although write can only be used on a single record (90% sure on this, not 100%).
> 
> ```python
> @api.multi
> def write(self, vals):
>     # Custom track visibility for
>     # taxes_id (M2M), seller_ids (M2M, supplier_taxes_id (O2M)
>     for rec in self:
>         ...
>         res = super(ProductTemplate, self).write(vals).   # called on self not rec !
>         ...
>     return res
> ```
> 
> could be
> 
> ```python
> @api.multi
> def write(self, vals):
>     # Custom track visibility for
>     # taxes_id (M2M), seller_ids (M2M, supplier_taxes_id (O2M)
>     ...
>     res = super(ProductTemplate, product).write(vals)
>     ...
>     return res
> ```

This is a good point and I don't know how to solve this yet...

2020-09-24 16:01 UTC, robinkeunen commented
We're in a custom module, if that passes functional tests, it's ok :-)

2020-09-24 16:01 UTC, robinkeunen approved these changes

2020-09-25 15:10 UTC, mclaeysb commented
With improvements as suggested by @remytms - *praised be his tallent*.

2020-09-28 11:18 UTC, robinkeunen approved these changes

2020-09-28 11:18 UTC, robinkeunen commented
nice

2020-10-26 13:44 UTC, merged