[ADD] coopiteasy_custom: Do not make closed projects selectable in tasks
coopiteasy/cie-custom pull request #67
Opened 2022-06-22 10:08 UTC by carmenbianca

## Description

## Odoo task (if applicable)

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

2022-06-22 12:03 UTC, huguesdk requested changes
would you please add a comment before the first `xpath` and move the current comment before the 2nd `xpath`?

2022-06-22 12:03 UTC, huguesdk commented on coopiteasy_custom/views/project_task.xml
> +                >[("active", "=", True), ("project_status.is_closed", "!=", False)]</attribute>
i don’t understand why this has to change, especially inverting the `is_closed` condition.

2022-06-22 12:03 UTC, huguesdk commented on coopiteasy_custom/views/project_task.xml
> +                >[("active", "=", True), ("project_status.is_closed", "=", False)]</attribute>
why `active = True`? this is by default.

2022-06-23 05:51 UTC, carmenbianca commented on coopiteasy_custom/views/project_task.xml
> +                >[("active", "=", True), ("project_status.is_closed", "!=", False)]</attribute>
inverted condition was a typo :x fixed

2022-06-23 05:52 UTC, carmenbianca commented on coopiteasy_custom/views/project_task.xml
> +                >[("active", "=", True), ("project_status.is_closed", "=", False)]</attribute>
I got the `active = True` condition from upstream's domain on project_id, but it appears to do exactly nothing, so I've reverted that change.

2022-06-23 08:43 UTC, huguesdk approved these changes
lgtm! 🚀 extra bonus if you change the comment as explained in my previous review. 😉

2022-06-23 13:43 UTC, remytms commented
/ocabot merge minor

2022-06-23 13:55 UTC, merged